### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Yasston** [SOM-Research/odata-generator#1]
Hello, the link you provide to install the plugin through Eclipse does not work anymore : https://som-research.github.io/odata-generator/update/

Could you please provide another way of installing the plugin ?

Thank you in advance.

**Comment by hamzaed** [comment]
Hi,
Thank you for trying to use the tool.
What do you mean by does not work anymore? I just checked the update site and it works. Can you please give more details about the problem.

Hamza

**Comment by Mabenan** [comment]
If some has a problem because eclipse doesn't show anything under available software you have to uncheck "Group items by category"

**Comment by hamzaed** [comment]
Getting a 404 page in the browser is just normal because the link is meant to be used in Eclipse. 
@Mabenan's trick is useful when Eclipse doesn't show anything under available software. Thank you @Mabenan for your contribution.

Hamza
